/* ===== REIS Logistica - Blog posts (auto-generated, real published posts) ===== */
window.REIS_POSTS = [
  {
    "slug": "costos-logisticos-competitividad-comercio-internacional",
    "title": "Costos logísticos: el factor silencioso que define la competitividad en el comercio internacional",
    "category": "Comercio Exterior",
    "cover": "https://static.wixstatic.com/media/78c590_bcb64713ea31402fb920674b6c071ac6~mv2.png/v1/fill/w_1200,h_750,al_c,q_88,enc_avif,quality_auto/78c590_bcb64713ea31402fb920674b6c071ac6~mv2.png",
    "excerpt": "En el comercio internacional, muchas empresas se concentran en variables visibles como precios, proveedores o aranceles. Pero hay un factor silencioso que define la rentabilidad y la competitividad: los costos logísticos…",
    "publishDate": "2026-06-25",
    "readTime": 6,
    "category_en": "Foreign Trade",
    "title_en": "Logistics costs: the silent factor that defines competitiveness in international trade",
    "excerpt_en": "In international trade, many companies focus on visible variables like prices, suppliers or tariffs. But a silent factor defines profitability and competitiveness: logistics costs…",
    "category_zh": "对外贸易",
    "title_zh": "物流成本：定义国际贸易竞争力的隐形因素",
    "excerpt_zh": "在国际贸易中，许多企业关注价格、供应商或关税等显性变量，但有一个隐形因素决定着盈利能力与竞争力：物流成本……"
  },
  {
    "slug": "logistica-t-mec-2026",
    "title": "Logística T-MEC 2026: cómo preparar las cadenas de suministro ante el nuevo equilibrio comercial de Norteamérica",
    "category": "Comercio Exterior",
    "cover": "https://static.wixstatic.com/media/bb3c90_42116936f21945949f423907acc01aee~mv2.png/v1/fill/w_1200,h_750,al_c,q_88,enc_avif,quality_auto/bb3c90_42116936f21945949f423907acc01aee~mv2.png",
    "excerpt": "La revisión del Tratado entre México, Estados Unidos y Canadá, mejor conocido como T-MEC, será uno de los procesos económicos más relevantes para las empresas…",
    "publishDate": "2026-06-02",
    "readTime": 6,
    "category_en": "Foreign Trade",
    "title_en": "USMCA Logistics 2026: how to prepare supply chains for North America's new trade balance",
    "excerpt_en": "The review of the treaty between Mexico, the United States and Canada, better known as the USMCA, will be one of the most relevant economic processes for companies…",
    "category_zh": "对外贸易",
    "title_zh": "USMCA 物流 2026：如何为北美新的贸易平衡做好供应链准备",
    "excerpt_zh": "墨西哥、美国与加拿大之间协定（即 USMCA / T-MEC）的审议，将是对相关企业最重要的经济进程之一……"
  },
  {
    "slug": "logistica-2026",
    "title": "Logística 2026: cómo operar ante cambios comerciales, aranceles y mayor volatilidad regulatoria",
    "category": "Logística",
    "cover": "https://static.wixstatic.com/media/78c590_07956ba0c96e4ecb81f98e273c98165c~mv2.jpg/v1/fill/w_1200,h_750,al_c,q_88,enc_avif,quality_auto/78c590_07956ba0c96e4ecb81f98e273c98165c~mv2.jpg",
    "excerpt": "La logística 2026 se perfila como uno de los temas más importantes para las empresas que participan en comercio exterior, importación, exportación,…",
    "publishDate": "2026-05-21",
    "readTime": 4,
    "category_en": "Logistics",
    "title_en": "Logistics 2026: how to operate amid trade shifts, tariffs and greater regulatory volatility",
    "excerpt_en": "Logistics in 2026 is shaping up to be one of the most important topics for companies involved in foreign trade, imports, exports,…",
    "category_zh": "物流",
    "title_zh": "物流 2026：在贸易变局、关税与更高监管波动下如何运营",
    "excerpt_zh": "2026 年的物流正成为参与对外贸易、进口与出口企业最重要的议题之一……"
  },
  {
    "slug": "inteligencia-artificial-logistica-mexico",
    "title": "Inteligencia artificial en logística en México: la transformación que redefine las cadenas de suministro",
    "category": "Tecnología",
    "cover": "https://static.wixstatic.com/media/78c590_3f5db52b7ae34c778a3015797f3a6aa0~mv2.png/v1/fill/w_1200,h_750,al_c,q_88,enc_avif,quality_auto/78c590_3f5db52b7ae34c778a3015797f3a6aa0~mv2.png",
    "excerpt": "La logística en México atraviesa una transformación profunda. Lo que durante décadas fue considerado un desafío operativo basado principalmente en…",
    "publishDate": "2026-05-07",
    "readTime": 4,
    "category_en": "Technology",
    "title_en": "Artificial intelligence in logistics in Mexico: the transformation reshaping supply chains",
    "excerpt_en": "Logistics in Mexico is undergoing a profound transformation. What for decades was seen as an operational challenge based mainly on…",
    "category_zh": "技术",
    "title_zh": "墨西哥物流中的人工智能：重塑供应链的变革",
    "excerpt_zh": "墨西哥的物流正经历深刻变革。几十年来，它一直被视为一项主要基于运营的挑战……"
  },
  {
    "slug": "mercado-transporte-carga-mexico-2026",
    "title": "Mercado de transporte de carga y logística en México crecerá 5.38% en 2026 impulsado por nearshoring y e-commerce",
    "category": "Logística",
    "cover": "https://static.wixstatic.com/media/78c590_4da700a6cfd04e0584ec178ff119164c~mv2.webp/v1/fill/w_1200,h_750,al_c,q_88,enc_avif,quality_auto/78c590_4da700a6cfd04e0584ec178ff119164c~mv2.webp",
    "excerpt": "El mercado de transporte de carga y logística en México continúa mostrando una trayectoria de crecimiento sostenido, consolidándose como uno de los pilares más…",
    "publishDate": "2026-04-23",
    "readTime": 4,
    "category_en": "Logistics",
    "title_en": "Mexico's freight and logistics market to grow 5.38% in 2026, driven by nearshoring and e-commerce",
    "excerpt_en": "Mexico's freight transport and logistics market continues to show sustained growth, consolidating itself as one of the most important pillars…",
    "category_zh": "物流",
    "title_zh": "墨西哥货运与物流市场 2026 年将增长 5.38%，由近岸外包与电商驱动",
    "excerpt_zh": "墨西哥货运与物流市场持续保持稳定增长，成为最重要的支柱之一……"
  },
  {
    "slug": "mercado-warehousing-mexico-2034",
    "title": "Mercado de warehousing en México: crecimiento, tecnología y oportunidades hacia 2034",
    "category": "Warehousing",
    "cover": "https://static.wixstatic.com/media/78c590_36725bb4d15a4995ad1e31a4891fce87~mv2.webp/v1/fill/w_1200,h_750,al_c,q_88,enc_avif,quality_auto/78c590_36725bb4d15a4995ad1e31a4891fce87~mv2.webp",
    "excerpt": "En los últimos años, el papel de una empresa logística en México ha evolucionado de forma significativa. Ya no se trata únicamente de mover mercancía de un…",
    "publishDate": "2026-04-08",
    "readTime": 4,
    "category_en": "Warehousing",
    "title_en": "Warehousing market in Mexico: growth, technology and opportunities toward 2034",
    "excerpt_en": "In recent years, the role of a logistics company in Mexico has evolved significantly. It is no longer only about moving goods from one…",
    "category_zh": "仓储",
    "title_zh": "墨西哥仓储市场：迈向 2034 年的增长、技术与机遇",
    "excerpt_zh": "近年来，墨西哥物流企业的角色发生了显著演变。如今已不再只是把货物从一处……"
  },
  {
    "slug": "foreign-trade-zones-exportadores",
    "title": "Foreign Trade Zones para exportadores: ventajas logísticas y fiscales en la frontera México–Estados Unidos",
    "category": "Comercio Exterior",
    "cover": "https://static.wixstatic.com/media/78c590_6fe4cc71752844b682abc3cffc321a7f~mv2.jpg/v1/fill/w_1200,h_750,al_c,q_88,enc_avif,quality_auto/78c590_6fe4cc71752844b682abc3cffc321a7f~mv2.jpg",
    "excerpt": "En el comercio internacional actual, la competitividad no depende únicamente de producir más rápido o vender más barato. Cada vez más, la ventaja estratégica…",
    "publishDate": "2026-03-05",
    "readTime": 5,
    "category_en": "Foreign Trade",
    "title_en": "Foreign Trade Zones for exporters: logistics and tax advantages on the Mexico–United States border",
    "excerpt_en": "In today's international trade, competitiveness does not depend solely on producing faster or selling cheaper. Increasingly, the strategic advantage…",
    "category_zh": "对外贸易",
    "title_zh": "面向出口商的对外贸易区（FTZ）：墨美边境的物流与税务优势",
    "excerpt_zh": "在当今的国际贸易中，竞争力不再仅取决于生产更快或售价更低。战略优势正越来越……"
  }
];
